### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by snake66**
Hey, here's a couple of fixes that makes the fuzzer build on a Linux system with the latest clang compiler. Also fixed some warnings, though there are more left. Let me know if you have any comments or issues with the patch.

### CODE REVIEW

**Comment by andrewffff** [comment]
Thanks, this looks useful. The stuff in `codecs/u8u16` is vendored from someone else - so I'm not sure if it's best to get a clean compile, versus leaving it verbatim in case people find the changes from upstream confusing. What do you think?

The stuff outside codecs/u8u16 is a clear win, I'd be happy to merge.

Thanks.

**Comment by andrewffff** [comment]
BTW depending on what you're up to, you may be interested in some newer developments from last year. https://github.com/lemire/fastvalidate-utf-8 and https://github.com/zwegner/faster-utf8-validator are newer libraries. Early versions of both libraries are included and benchmarked in the 2019_compare branch.

**Comment by snake66** [comment]
> The stuff in `codecs/u8u16` is vendored from someone else

I suspected as much. I'll drop those changes then, and make a new push with only the changes in the base.

For the moment I was just wanting to compile the project to see if it was useful to me. Thought I'd pass up the fixes since I had to make them to make it compile anyways. I'm looking for a tool to help me find strings that will be parsed differently in different utf8 implementations for pentesting purposes.

**Comment by andrewffff** [comment]
LGTM, thanks!

**Pull request merged**
